# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc325a6048fb21274c5052e6041c2688c54ddab09cb872d4d7a72131ae82d7f11c4aa0ac6051a1b3aca96e4974461f5e2a795a90b90c38b4da18f47753d38ba2

test:
  secret_key_base: eaa39a54a35793d4bf993fc12c8a4207d80626444e3b2cca577048c5df20549bfd0581ae66b2560977932de35754f4fe6747a04b46a61afee86764af2e878f1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
